Update android-installation.mdx
mirrorworld-universe/docs.mirrorworld.fun pull request #73
Opened 2022-12-12 12:53 UTC by SuQiang2007

2022-12-13 10:10 UTC, ChuckD30 requested changes
hey @SuQiang2007 I've suggested and requested the following changes. Thanks

2022-12-13 10:10 UTC, ChuckD30 commented on data/android/android-installation.mdx
> +If you want to use CustomTab to show content to users(Recommand), you need to config the following contents on your AndroidManifest.xml:
```suggestion
If you want to use CustomTab to show content to users (Recommended), you need to configure the following on your AndroidManifest.xml:
```

2022-12-13 10:10 UTC, ChuckD30 commented on data/android/android-installation.mdx
> +So, the finnaly file would looked as this:
```suggestion
The final file would look like this:
```

2022-12-13 10:10 UTC, ChuckD30 commented on data/android/android-installation.mdx
> +**Add dependence**
```suggestion
**Add dependency**
```

2022-12-13 10:10 UTC, ChuckD30 commented on data/android/android-installation.mdx
> +And then, you will see CustomTab when you try to open our prepared web page.
```suggestion
You should now see CustomTab when you try to open our prepared web page.
```

2022-12-13 10:10 UTC, ChuckD30 commented on data/android/android-installation.mdx
> +>*Tips:If you want to make your app has only one task, you can set your own activity to SingTast:*
```suggestion
>*Tips: If you want your app to have only one task, you can set your own activity to SingTast:*
```

2022-12-13 10:10 UTC, ChuckD30 commented on data/android/android-installation.mdx
>  If you want them to login(or again), you can use the following code:
```suggestion
If you want them to login for the first time or once again, use the following code:
```

2022-12-13 10:10 UTC, ChuckD30 commented on data/android/android-installation.mdx
>  Users may want to check their wallet in the app, you can use openWallet API:
```suggestion
Users may want to check their wallet in the app, you can use the `openWallet` API for this:
```

2022-12-19 02:11 UTC, SuQiang2007 commented
Have complete all the comments.

2022-12-23 04:11 UTC, merged