iOS document
mirrorworld-universe/docs.mirrorworld.fun pull request #76
Opened 2022-12-13 14:05 UTC by hellozmg

first ios document commit.

2022-12-14 14:06 UTC, ChuckD30 requested changes
Please fix the following requested changes @hellozmg

2022-12-14 14:06 UTC, ChuckD30 commented on data/ios/ios-api.mdx
> +Calling this api would popup a dialog, user can finish login flow on it. In which dialog, user can login with third method like google, twitter. Or he can login with his email which registered on our
```suggestion
Calling this API would popup a dialog, user can finish login flow on it. In which the user can login with another method like Google or Twitter. Or they can login with their registered email.
```

2022-12-14 14:06 UTC, ChuckD30 commented on data/ios/ios-api.mdx
> +Checks whether the current user is logged in. You can use this function to judge whether a user needs to start login flow.
```suggestion
Checks whether the current user is logged in. You can use this function to check if a user needs to start the login flow.
```

2022-12-14 14:06 UTC, ChuckD30 commented on data/ios/ios-api.mdx
> +Open a webview which would show the wallet page.
```suggestion
Opens a web view which shows the wallet page.
```

2022-12-14 14:06 UTC, ChuckD30 commented on data/ios/ios-api.mdx
> +Get access token so that users can visit APIs.
```suggestion
Gets access token for users to use the API.
```

2022-12-14 14:06 UTC, ChuckD30 commented on data/ios/ios-installation.mdx
> +init SDK in the AppDelegate.
```suggestion
initialize SDK in the AppDelegate.
```

2022-12-14 14:06 UTC, ChuckD30 commented on data/ios/ios-authentication.mdx
> +Token saved in local by SDK would be out of date. So when a user opens the app, the developer should check his authentication every time. If token is invalidate, we should guild users to login again.
```suggestion
Token saved locally by SDK would be out of date. So when a user opens the app, they should check their authentication every time. If the token is invalidated, we should guide users to login again.
```

2022-12-15 03:13 UTC, hellozmg commented on data/ios/ios-api.mdx
> +Calling this api would popup a dialog, user can finish login flow on it. In which dialog, user can login with third method like google, twitter. Or he can login with his email which registered on our
Okay, I'll fix it today.

2022-12-15 18:00 UTC, codebender828 approved these changes

2022-12-15 18:01 UTC, merged