Create unity-installation.mdx
mirrorworld-universe/docs.mirrorworld.fun pull request #80
Opened 2022-12-19 02:15 UTC by SuQiang2007

2022-12-19 02:28 UTC, codebender828 requested changes
Looks mostly good. Made some suggestions:
1. Typo in the word `Package`.
2. Let's not add the API Reference to the installation page. Since we already link the user to the Unity API Reference, there is no need to add more docs for those functions on the installation page. If you feel that we need to guide them somehow, then maybe you can use links to direct them to that resource on the docs.

Let's fix the above two and I can merge it 👍🏽

2022-12-19 02:28 UTC, codebender828 commented on data/unity/unity-installation.mdx
> +### Packge
```suggestion
### Package
```

2022-12-19 02:28 UTC, codebender828 commented on data/unity/unity-installation.mdx
> +Find File->Build and settings->Choose Android platform(If you are not)->Click switch platform button.
```suggestion
Find File -> Build and settings -> Choose Android platform (If you are not) -> Click switch platform button.`
```

2022-12-19 02:28 UTC, codebender828 commented on data/unity/unity-installation.mdx
> +- The param 'conformation' is a confirmation with chain,you can learn it from its explanation in this document.
@SuQiang2007 I think we don't need to put these here if they are already on the API reference page for the Unity SDK. Let's keep this page dedicated to installation.

2022-12-22 08:09 UTC, SuQiang2007 commented on data/unity/unity-installation.mdx
> +- The param 'conformation' is a confirmation with chain,you can learn it from its explanation in this document.
Thanks, I have removed some API explanation including list/transfer/fetchNFT.

2022-12-23 04:09 UTC, codebender828 approved these changes

2022-12-23 04:14 UTC, merged